export const innerspagesListData = {
    emptyMessage: "No inner pages available at the moment.",
    defaultAltText: "Inner page",
    subtitle: "Inner pages",
    title: "take a look at the Inner pages",
    divider: true,
    align: "center" as const,
    items: [
        // Restaurant
        {
            id: 1,
            image: "/sections/page-menu.webp",
            altText: "Menu page preview",
            link: "/menu",
            caption: "Menu",
            group: "Restaurant",
        },
        {
            id: 2,
            image: "/sections/page-menu-tabs.webp",
            altText: "Menu tabs page preview",
            link: "/menu-tabs",
            caption: "Menu Tabs",
            group: "Restaurant",
        },
        {
            id: 3,
            image: "/sections/page-menu-full-width.webp",
            altText: "Menu full width page preview",
            link: "/menu-full-width",
            caption: "Menu Full Width",
            group: "Restaurant",
        },
        {
            id: 4,
            image: "/sections/page-menu-sidebar.webp",
            altText: "Menu Sidebar page preview",
            link: "/menu-sidebar",
            caption: "Menu Sidebar",
            tag: "New",
            group: "Restaurant",
        },
        // About
        {
            id: 5,
            image: "/sections/page-about.webp",
            altText: "About Us page preview",
            link: "/about-us",
            caption: "About Us",
            group: "About",
        },
        {
            id: 6,
            image: "/sections/page-history.webp",
            altText: "History page preview",
            link: "/history",
            caption: "History",
            group: "About",
        },
        {
            id: 7,
            image: "/sections/page-team.webp",
            altText: "Chefs page preview",
            link: "/chefs",
            caption: "Chefs",
            group: "About",
        },
        {
            id: 8,
            image: "/sections/page-services.webp",
            altText: "Services page preview",
            link: "/services",
            caption: "Services",
            group: "About",
        },
        {
            id: 9,
            image: "/sections/page-contact.webp",
            altText: "Contact page preview",
            link: "/contact-us",
            caption: "Contact",
            group: "About",
        },
        // Utility
        {
            id: 10,
            image: "/sections/page-blog.webp",
            altText: "Blog page preview",
            link: "/blog",
            caption: "Blog",
            group: "Utility",
        },
        {
            id: 11,
            image: "/sections/page-comming-soon.webp",
            altText: "Coming soon page preview",
            link: "/coming-soon",
            caption: "Coming Soon",
            group: "Utility",
        },
        {
            id: 12,
            image: "/sections/page-404.webp",
            altText: "404 page preview",
            link: "/404",
            caption: "404",
            group: "Utility",
        },
    ],
};
