export const galleryData = {
	subtitle: "Our Gallery",
	title: "Explore The New Tastee",
	phrase:
		"The first restaurant proprietor is believed to have been one A. Boulanger, a soup vendor, who opened his business in 1765.",
	divider: true,
	align: "center",
	emptyMessage: "No gallery items available at the moment.",
	errorMessage: "Error loading gallery:",
	lightboxOpenLabel: "Open lightbox",
	lightboxPrevAriaLabel: "Previous image",
	lightboxNextAriaLabel: "Next image",
	lightboxCloseAriaLabel: "Close lightbox",
	items: [
		{
			id: 1,
			image: "/gallery/gallery-1a.webp",
			title: "Spring Roll",
			altText: "Restaurant gallery showcase",
			subtitle: "Food",
		},
		{
			id: 2,
			image: "/gallery/gallery-2a.webp",
			title: "Dinner Series",
			altText: "Culinary experience highlights",
			subtitle: "Food",
		},
		{
			id: 3,
			image: "/gallery/gallery-3a.webp",
			title: "Bevereges",
			altText: "Restaurant ambiance and decor",
			subtitle: "Drinks",
		},
		{
			id: 4,
			image: "/gallery/gallery-4a.webp",
			title: "Great Moments",
			altText: "Dining experience moments",
			subtitle: "Events",
		},
		{
			id: 5,
			image: "/gallery/gallery-5a.webp",
			title: "Beautiful Spaces",
			altText: "Restaurant interior and dining ambiance",
			subtitle: "Locations",
		},
		{
			id: 6,
			image: "/gallery/gallery-6a.webp",
			title: "Pleasant Spaces",
			altText: "Fine dining table setting and atmosphere",
			subtitle: "Locations",
		},
		{
			id: 7,
			image: "/gallery/gallery-7a.webp",
			title: "House Recipe",
			altText: "Signature dishes and culinary presentations",
			subtitle: "Food",
		},
		{
			id: 8,
			image: "/gallery/gallery-8a.webp",
			title: "Food and Wine",
			altText: "Restaurant bar and beverage selection",
			subtitle: "Events",
		},
	],
};
