export const innerspagesListData = {
	emptyMessage: "No inner pages available at the moment.",
	defaultAltText: "Inner page",
	subtitle: "Inner pages",
	title: "take a look at the Inner pages",
	divider: true,
	align: "center" as const,
	items: [
		{
			id: 1,
			image: "/sections/page-about.webp",
			altText: "About Us page preview",
			link: "/about-us",
			caption: "About Us",
		},
		{
			id: 2,
			image: "/sections/page-history.webp",
			altText: "History page preview",
			link: "/history",
			caption: "History",
		},
		{
			id: 3,
			image: "/sections/page-menu.webp",
			altText: "Menu page preview",
			link: "/menu",
			caption: "Menu",
		},
		{
			id: 4,
			image: "/sections/page-menu-tabs.webp",
			altText: "Menu tabs page preview",
			link: "/menu-tabs",
			caption: "Menu tabs",
		},
		{
			id: 5,
			image: "/sections/page-menu-full-width.webp",
			altText: "Menu full width page preview",
			link: "/menu-full-width",
			caption: "Menu full width",
		},
		{
			id: 6,
			image: "/sections/page-menu-sidebar.webp",
			altText: "Menu Sidebar page preview",
			link: "/menu-sidebar",
			caption: "Menu Sidebar",
			tag: "New",
		},
		{
			id: 7,
			image: "/sections/page-blog.webp",
			altText: "Blog page preview",
			link: "/blog",
			caption: "Blog",
		},
		{
			id: 8,
			image: "/sections/page-comming-soon.webp",
			altText: "Coming soon page preview",
			link: "/coming-soon",
			caption: "Coming soon",
		},
		{
			id: 9,
			image: "/sections/page-404.webp",
			altText: "404 page preview",
			link: "/404",
			caption: "404",
		},
	],
};
